CREATE TRIGGER tr_participacao_tot AFTER INSERT
ON jogador
FOR EACH ROW
SET NEW.PART_TOT = (NEW.GOLS_JOG + NEW.ASSIST_JOG)
; 

CREATE TRIGGER tr_aproveitamento BEFORE INSERT
ON tecnico
FOR EACH ROW
SET NEW.APROVEITAMENTO = (NEW.VIT_TEC / NEW.JOGOS_TEC) /100
; 


CREATE PROCEDURE VERIFICAR_QTD_JOG(OUT QTD_JOG INT)
BEGIN
SELECT COUNT() INTO QTD_JOG FROM jogador;
END $$
DELIMITER ;

DELIMITER $$

CREATE PROCEDURE VERIFICAR_QTD_TEC(OUT QTD_TEC INT)
BEGIN
SELECT COUNT() INTO QTD_TEC FROM tecnico;
END $$
DELIMITER ;


CALL VERIFICAR_QTD_TEC(@p0); SELECT @p0 AS QTD_TEC;
CALL VERIFICAR_QTD_JOG(@p0); SELECT @p0 AS QTD_JOG; 
