INSERT INTO CONTINENTE (COD_CONTINENTE, NOME_ASSOC, NOME_CONT)
VALUES (1, 'CONMEBOL', 'América do Sul')
;
INSERT INTO pais (COD_PAIS, COD_CONTINENTE, NOME_PAIS)
VALUES ('BR', 1, 'Brasil')
;
INSERT INTO liga (COD_LIGA, COD_PAIS, NOME_LIGA)
VALUES (1, 'BR', 'Brasileirão Série A')
;
INSERT INTO time (COD_TIME, COD_LIGA, NOME_TIME)
VALUES ('INT', 1, 'Sport Club Internacional')
;

INSERT INTO jogador(COD_JOGADOR, COD_TIME, COD_LIGA, NOME_JOG, IDADE_JOG, NAC_JOG, JOGOS_JOG, GOLS_JOG, ASSIST_JOG)
VALUES (1, 'INT', 1, 'Taison Barcellos Freda', 34, 'Brasileiro', 8, 2, 2)
;

INSERT INTO tecnico (COD_TECNICO, COD_TIME, COD_LIGA, NOME_TEC, IDADE_TEC, NAC_TEC, JOGOS_TEC, VIT_TEC, EMP_TEC, DER_TEC)
VALUES (1, 'INT', 1, 'Alexander Jesús Medina Reobasco', 43, 'Uruguaio', 16, 6, 5, 5)
;

